### ISSUE TITLE
The stream option is not working. 

### ISSUE THREAD

**Issue by Huvinesh-Rajendran-12** [moesmufti/xai_grok_sdk#1]
When I set stream to True in the invoke API, I am getting the following error : 

`---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/Documents/grok_projects/.venv/lib/python3.12/site-packages/requests/models.py:974, in Response.json(self, **kwargs)
    973 try:
--> 974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
File /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py:346, in l
oads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
File /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py:338, in JS
ONDecoder.decode(self, s, _w)
    334 """Return the Python representation of ``s`` (a ``str`` instance
    335 containing a JSON document).
    336
    337 """
--> 338 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    339 end = _w(s, end).end()
File /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py:356, in JS
ONDecoder.raw_decode(self, s, idx)
    355 except StopIteration as err:
--> 356     raise JSONDecodeError("Expecting value", s, err.value) from None
    357 return obj, end
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
JSONDecodeError                           Traceback (most recent call last)
Cell In[10], line 1
----> 1 response = xai.invoke(
      2     messages=[
      3         {
      4             "role": "user",
      5             "content": "What is the capital of France?"
      6         }
      7     ],
      8     stream=True
      9 )
File ~/Documents/grok_projects/.venv/lib/python3.12/site-packages/xai_grok_sdk/xai.py:141, in XAI.invoke(self, messages, frequen
cy_penalty, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, stream_options, temperat
ure, tool_choice, top_logprobs, top_p, user)
    118 payload = ChatCompletionRequest(
    119     messages=messages,
    120     model=self.model,
   (...)
    137     user=user,
    138 ).__dict__
    140 # Make API call
--> 141 response_data = self._make_api_call(payload)
    143 # Handle tool calls if present
    144 if "choices" in response_data and len(response_data["choices"]) > 0:
File ~/Documents/grok_projects/.venv/lib/python3.12/site-packages/xai_grok_sdk/xai.py:70, in XAI._make_api_call(self, payload)
     66 response = requests.post(
     67     f"{self.base_url}/chat/completions", headers=headers, json=payload
     68 )
     69 response.raise_for_status()
---> 70 return response.json()
File ~/Documents/grok_projects/.venv/lib/python3.12/site-packages/requests/models.py:978, in Response.json(self, **kwargs)
    974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 978     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

The error is occurring when the _make_api_call function is called with the payload.

**Comment by moesmufti** [comment]
Hello, could you maybe give me a sample payload that you used to get this error so I can reproduce?

**Comment by moesmufti** [comment]
Went ahead and simply tried a payload, found the issue. Now streaming is fully supported in v0.0.11, including documentation in the readme! Please let me know if you face any other issues (reopen if you need)

**Comment by Huvinesh-Rajendran-12** [comment]
Sure, will try and let you know. Thanks.
